# Generated by Django 4.1.7 on 2023-03-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwitter', '0005_gweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gweet',
            name='body',
            field=models.CharField(max_length=140),
        ),
    ]
